version: '2'
services:
  catinygateway-mariadb:
    extends:
      file: mariadb.yml
      service: catinygateway-mariadb
  catinygateway-redis:
    extends:
      file: redis.yml
      service: catinygateway-redis
  catinygateway-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: catinygateway-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_PRIVATE://kafka:9092,LISTENER_PUBLIC://dev.catiny.com:10400
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
